# Generated by Django 5.2.3 on 2025-06-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_delivery_boy_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coin_balance',
            field=models.IntegerField(default=0),
        ),
    ]
