# Generated by Django 5.2.3 on 2025-06-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofile_coin_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coin_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
